version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stream_db
    ports:
      - "5432:5432" ## 5432 is the default port for PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server --requirepass streamerroom_keydb_password
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
      
  server:
    build:
      context: .
      dockerfile: apps/server/dockerfile
    depends_on:
      - db
      - keydb
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/stream_db
      - KEYDB_URL=redis://:streamerroom_keydb_password@keydb:6379
    ports:
      - "8000:8000"
    volumes:
      - ./apps/server:/app
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
  keydb_data:
